name: Frontend → Tester (remote build)

on:
  push:
    branches: ["dev"]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: self-hosted
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - name: Set target
        run: |
          echo HOST=${{ secrets.TARGET_HOST }} >> $GITHUB_ENV
          echo USER=${{ secrets.TARGET_USER }} >> $GITHUB_ENV
          echo PORT=${{ secrets.TARGET_SSH_PORT || 22 }} >> $GITHUB_ENV

      - name: Write SSH key & test
        shell: bash
        run: |
          mkdir -p "${{ runner.temp }}"
          KEY="${{ secrets.TARGET_SSH_KEY }}"
          printf '%s\n' "$KEY" | sed 's/\r$//' > "${{ runner.temp }}/k"
          chmod 600 "${{ runner.temp }}/k"
          ssh -i "${{ runner.temp }}/k" -p "$PORT" -o StrictHostKeyChecking=no "$USER@$HOST" echo ok

      - name: Sync code to Tester (/opt/brainboost/src/frontend)
        shell: bash
        run: |
          RSYNC_RSH="ssh -i ${{ runner.temp }}/k -p $PORT -o StrictHostKeyChecking=no"
          ssh -i "${{ runner.temp }}/k" -p "$PORT" -o StrictHostKeyChecking=no "$USER@$HOST" "mkdir -p /opt/brainboost/src/frontend"
          rsync -az --delete --exclude ".git" --exclude "node_modules" --exclude ".github" \
            -e "$RSYNC_RSH" ./ "$USER@$HOST:/opt/brainboost/src/frontend/"

      - name: Build & up frontend on 3000
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USER }}
          key: ${{ secrets.TARGET_SSH_KEY }}
          port: ${{ env.PORT }}
          script: |
          
            docker ps --filter "name=brainboost-front" -q | xargs -r docker rm -f || true

            
            docker compose -f /home/tester/BrainBoostFront/docker-compose.dev.yml build web

            
            docker compose -f /home/tester/BrainBoostFront/docker-compose.dev.yml up -d --force-recreate web
